# SPDX-License-Identifier: GPL-2.0
#
#  Makefile for the Linux Local Interconnect Network core.
#

obj-$(CONFIG_LIN)	+= lin.o
lin-y			:= af_lin.o dev.o

obj-$(CONFIG_LIN_RAW)	+= lin-raw.o
lin-raw-y		:= raw.o
