# SPDX-License-Identifier: GPL-2.0
#
#  Makefile for the Linux Local Interconnect Network drivers.
#

obj-$(CONFIG_LIN_SLLIN)		+= sllin/
#TODO: vlin.o

# obj-y				+= dev/
# obj-y				+= spi/
# obj-y				+= usb/

subdir-ccflags-$(CONFIG_LIN_DEBUG_DEVICES) += -DDEBUG